import React,{useEffect,useState} from 'react';
import {ArrowLeft,HelpCircle,Trophy,Users} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import Layout from '../components/Layout/Layout';import api from '../utils/api';
const money=v=>v?`₩ ${Number(v).toLocaleString()}`:'-';
export default function BidResultDetail(){const {id}=useParams();const nav=useNavigate();const [item,setItem]=useState(null);useEffect(()=>{api.get(`/bid-results/${id}`).then(r=>setItem(r.data.item));},[id]);if(!item)return <Layout><div className="dashboard-container">결과를 불러오는 중입니다...</div></Layout>;const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:12,padding:22};return <Layout><div className="dashboard-container"><button onClick={()=>nav('/results')} style={{display:'flex',gap:6,alignItems:'center',color:'#64748b',marginBottom:20}}><ArrowLeft size={17}/>개찰결과 목록</button><span style={{padding:'4px 9px',borderRadius:12,background:'#dcfce7',color:'#166534',fontSize:12,fontWeight:800}}>{item.result_status}</span><h1 style={{fontSize:25,lineHeight:1.4,margin:'12px 0 6px'}}>{item.title}</h1><p style={{color:'#64748b',marginBottom:24}}>공고 번호 : {item.notice_no} · {item.org_name} · {item.opened_at}</p>
<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:20}}><Metric label="최종 낙찰기업" value={item.winner_name} icon={<Trophy/>}/><Metric label="낙찰금액" value={money(item.winning_amount)}/><Metric label="낙찰률" value={`${item.success_rate}%`}/><Metric label="참여업체" value={`${item.participant_count}개사`} icon={<Users/>}/></div>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginBottom:20}}><section style={card}><h2 style={{fontSize:17,marginBottom:16}}>가격 분석</h2>{[['기초금액',money(item.base_amount),'발주기관이 가격 산정을 위해 먼저 공개한 기준금액'],['예정가격',money(item.estimated_price),'개찰 과정에서 낙찰 판단에 사용되는 기준가격'],['최종 낙찰금액',money(item.winning_amount),'최종 낙찰기업이 제출한 금액'],['자사 투찰금액',money(item.my_bid_amount),item.my_bid_amount?`낙찰기업보다 ${money(item.my_bid_amount-item.winning_amount)} 높음`:'해당 입찰에 참여하지 않음']].map(([l,v,h])=><div key={l} style={{display:'flex',justifyContent:'space-between',padding:'13px 0',borderBottom:'1px solid #f1f5f9'}}><div><strong>{l}</strong><div style={{fontSize:11,color:'#94a3b8',marginTop:4}}>{h}</div></div><b>{v}</b></div>)}</section><section style={card}><h2 style={{fontSize:17,marginBottom:16}}>자사 결과</h2>{item.my_rank?<><div style={{fontSize:42,fontWeight:800,color:'#2563eb'}}>{item.my_rank}위</div><p style={{color:'#64748b',marginTop:8,lineHeight:1.6}}>총 {item.participant_count}개 참여업체 중 {item.my_rank}위입니다. 낙찰기업과의 가격 차이를 다음 입찰 전략에 참고할 수 있습니다.</p></>:<p style={{color:'#64748b'}}>이 공고에는 자사가 참여하지 않았습니다.</p>}</section></div>
<section style={card}><h2 style={{fontSize:17,marginBottom:16}}>참여업체 주요 순위</h2><table><thead><tr><th>순위</th><th>업체명</th><th>투찰금액</th><th>투찰률</th><th>결과</th></tr></thead><tbody>{item.bidders.map((b,i)=><tr key={i} style={{background:b.status==='자사'?'#eff6ff':'transparent'}}><td>{b.rank}위</td><td style={{fontWeight:700}}>{b.name}</td><td>{money(b.amount)}</td><td>{b.rate?`${b.rate}%`:'-'}</td><td>{b.status}</td></tr>)}</tbody></table></section>
<section style={{...card,marginTop:20,background:'#f8fafc'}}><h2 style={{fontSize:15,display:'flex',alignItems:'center',gap:7}}><HelpCircle size={17}/>용어 안내</h2><p style={{fontSize:13,color:'#64748b',lineHeight:1.8,marginTop:10}}>기초금액은 발주기관이 먼저 공개하는 가격 산정 기준이며, 예정가격은 개찰 과정에서 낙찰 판단에 사용하는 기준가격입니다. 개찰 1순위는 추가 자격심사 결과에 따라 최종 낙찰자가 되지 않을 수도 있습니다.</p></section></div></Layout>}
function Metric({label,value,icon}){return <div style={{background:'#fff',border:'1px solid #e2e8f0',borderRadius:12,padding:20}}><div style={{fontSize:13,color:'#64748b',display:'flex',gap:6}}>{icon&&React.cloneElement(icon,{size:16})}{label}</div><strong style={{display:'block',fontSize:19,marginTop:10}}>{value}</strong></div>}
