import React, { useEffect, useState } from 'react';
import { ArrowLeft, Calendar, Coins, Download, ExternalLink, Heart, Landmark } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import Layout from '../components/Layout/Layout';
import api from '../utils/api';

export default function SpecificationDetail(){
  const {id}=useParams(); const navigate=useNavigate(); const [spec,setSpec]=useState(null);
  useEffect(()=>{api.get(`/specifications/${id}`).then(r=>setSpec(r.data.item));},[id]);
  const toggle=async()=>{const {data}=await api.post(`/specifications/${id}/interest`);setSpec(s=>({...s,is_interest:data.is_interest}));};
  if(!spec)return <Layout><div className="dashboard-container">사전규격 정보를 불러오는 중입니다...</div></Layout>;
  const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:12,padding:24};
  return <Layout><div className="dashboard-container"><button onClick={()=>navigate('/specifications')} style={{display:'flex',alignItems:'center',gap:6,color:'#64748b',marginBottom:20}}><ArrowLeft size={17}/>사전규격 목록</button>
    <div style={{display:'flex',justifyContent:'space-between',gap:24,marginBottom:24}}><div><div style={{display:'flex',gap:8,marginBottom:10}}><span style={{padding:'4px 9px',borderRadius:12,background:'#f3e8ff',color:'#7e22ce',fontSize:12,fontWeight:800}}>사전규격</span><span style={{padding:'4px 9px',borderRadius:12,background:'#dcfce7',color:'#166534',fontSize:12,fontWeight:800}}>{spec.status}</span></div><h1 style={{fontSize:25,lineHeight:1.4}}>{spec.title}</h1><p style={{color:'#64748b',marginTop:8}}>사전규격 번호 : {spec.spec_no}</p></div><div style={{display:'flex',gap:8,alignItems:'flex-start'}}><button onClick={toggle} style={{height:42,padding:'0 15px',border:'1px solid #fecaca',borderRadius:8,color:'#dc2626',display:'flex',alignItems:'center',gap:6,fontWeight:700}}><Heart size={17} fill={spec.is_interest?'#dc2626':'none'}/>{spec.is_interest?'관심 해제':'관심 등록'}</button><button onClick={()=>window.open(spec.detail_url,'_blank')} style={{height:42,padding:'0 15px',borderRadius:8,background:'#0f172a',color:'#fff',display:'flex',alignItems:'center',gap:6,fontWeight:700}}><ExternalLink size={17}/>나라장터 원문</button></div></div>
    <div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:20}}><div style={{display:'grid',gap:20}}><section style={card}><h2 style={{fontSize:17,marginBottom:15}}>사업 개요 및 주요 규격</h2><p style={{lineHeight:1.8,color:'#475569',whiteSpace:'pre-wrap'}}>{spec.summary}</p></section><section style={card}><h2 style={{fontSize:17,marginBottom:15}}>참여 예상 자격</h2><p style={{lineHeight:1.7,color:'#475569'}}>{spec.qualification}</p><div style={{marginTop:14,padding:12,background:'#fffbeb',color:'#92400e',borderRadius:8,fontSize:13}}>사전규격 단계의 조건이며 정식 공고에서 변경될 수 있습니다.</div></section><section style={card}><h2 style={{fontSize:17,marginBottom:15}}>첨부파일</h2>{spec.attachments.map(file=><button key={file} style={{width:'100%',display:'flex',justifyContent:'space-between',padding:'12px 14px',borderBottom:'1px solid #e2e8f0'}}><span>{file}</span><Download size={17} color="#2563eb"/></button>)}</section></div>
    <aside style={{display:'grid',gap:14,alignContent:'start'}}><section style={card}><Info icon={<Landmark/>} label="발주기관" value={spec.org_name}/><Info icon={<Coins/>} label="배정 예산" value={`₩ ${Number(spec.estimated_price).toLocaleString()}`}/><Info icon={<Calendar/>} label="공개일" value={spec.posted_at}/><Info icon={<Calendar/>} label="의견제출 마감" value={spec.deadline_at} danger/></section><section style={card}><h3 style={{fontSize:15,marginBottom:10}}>정식 공고 전환</h3><p style={{fontSize:13,color:'#64748b',lineHeight:1.6}}>{spec.converted_notice_id?'정식 입찰공고가 게시되었습니다.':'아직 연결된 정식 입찰공고가 없습니다.'}</p>{spec.converted_notice_id&&<button onClick={()=>navigate(`/notice/${spec.converted_notice_id}`)} style={{width:'100%',height:40,marginTop:12,background:'#2563eb',color:'#fff',borderRadius:8,fontWeight:700}}>정식 공고 보기</button>}</section></aside></div>
  </div></Layout>;
}
function Info({icon,label,value,danger}){return <div style={{display:'flex',gap:10,padding:'12px 0',borderBottom:'1px solid #f1f5f9'}}>{React.cloneElement(icon,{size:17,color:'#64748b'})}<div><div style={{fontSize:12,color:'#94a3b8'}}>{label}</div><strong style={{display:'block',marginTop:4,fontSize:14,color:danger?'#dc2626':'#334155'}}>{value}</strong></div></div>}
