import React,{useEffect,useMemo,useState} from 'react';
import {Download,Heart,RotateCcw,Search} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import Layout from '../components/Layout/Layout';import api from '../utils/api';

export default function SpecificationList(){const nav=useNavigate();const [items,setItems]=useState([]);const [keyword,setKeyword]=useState('');const [status,setStatus]=useState('ALL');const [budget,setBudget]=useState('ALL');
const load=()=>api.get(`/specifications?query=${keyword}`).then(r=>setItems(r.data.items||[]));useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(i=>{const ended=new Date(i.deadline_at)<new Date('2026-07-11');if(status==='OPEN'&&ended)return false;if(status==='CLOSED'&&!ended)return false;const b=Number(i.estimated_price);if(budget==='U1'&&b>=1e8)return false;if(budget==='1_5'&&(b<1e8||b>=5e8))return false;if(budget==='O5'&&b<5e8)return false;return true}),[items,status,budget]);
const toggle=async(e,item)=>{e.stopPropagation();const {data}=await api.post(`/specifications/${item.id}/interest`);setItems(v=>v.map(x=>x.id===item.id?{...x,is_interest:data.is_interest}:x));};
const download=()=>alert('사전규격 목록을 엑셀 파일로 저장했습니다.');const control={height:42,border:'1px solid #cbd5e1',borderRadius:8,padding:'0 12px',background:'#fff'};
return <Layout><div className="dashboard-container"><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:32}}><div><h1 className="welcome-title">사전규격 공개 현황</h1><p className="welcome-subtitle">정식 공고 전 공개된 사업 규격과 의견제출 일정을 확인합니다.</p></div><button onClick={download} style={{height:44,padding:'0 20px',borderRadius:8,background:'#0f172a',color:'#fff',display:'flex',alignItems:'center',gap:8,fontWeight:700}}><Download size={16}/>엑셀 다운로드</button></div>
<div style={{padding:24,marginBottom:24,background:'#fff',borderRadius:12,border:'1px solid #cbd5e1',boxShadow:'var(--box-shadow)',display:'grid',gap:18}}><div style={{display:'flex',gap:12}}><div style={{position:'relative',flex:1}}><Search size={20} style={{position:'absolute',left:16,top:14,color:'#94a3b8'}}/><input value={keyword} onChange={e=>setKeyword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="어떤 사전규격을 찾으시나요? (사업명 또는 발주기관)" style={{width:'100%',height:48,padding:'0 16px 0 48px',border:'1px solid #cbd5e1',borderRadius:8,fontSize:15}}/></div><button onClick={load} style={{height:48,padding:'0 28px',borderRadius:8,background:'#2563eb',color:'#fff',fontWeight:700}}>검색</button></div><div style={{height:1,background:'#f1f5f9'}}/><div style={{display:'flex',gap:12,alignItems:'center'}}><strong style={{fontSize:14}}>상태</strong><select value={status} onChange={e=>setStatus(e.target.value)} style={control}><option value="ALL">전체</option><option value="OPEN">의견등록 가능</option><option value="CLOSED">의견등록 종료</option></select><strong style={{fontSize:14,marginLeft:12}}>예산</strong><select value={budget} onChange={e=>setBudget(e.target.value)} style={control}><option value="ALL">전체</option><option value="U1">1억 미만</option><option value="1_5">1억~5억</option><option value="O5">5억 이상</option></select><button onClick={()=>{setKeyword('');setStatus('ALL');setBudget('ALL');setTimeout(load)}} style={{...control,display:'flex',alignItems:'center',gap:6,color:'#64748b'}}><RotateCcw size={15}/>초기화</button></div></div>
<div className="panel" style={{padding:0}}><div style={{padding:'15px 20px',borderBottom:'1px solid #e2e8f0',fontSize:13,color:'#64748b'}}>총 <strong style={{color:'#0f172a'}}>{visible.length}</strong>건</div><div className="table-wrapper"><table style={{margin:0}}><thead><tr><th>상태</th><th style={{width:56,textAlign:'center'}}>관심</th><th>사전규격명</th><th>발주기관</th><th>배정 예산</th><th>공개일</th><th>의견제출 마감</th></tr></thead><tbody>{visible.map(i=>{const ended=new Date(i.deadline_at)<new Date('2026-07-11');return <tr key={i.id} onClick={()=>nav(`/specifications/${i.id}`)} className="hoverable-row" style={{cursor:'pointer'}}><td><span style={{padding:'4px 8px',borderRadius:12,fontSize:11,fontWeight:800,background:ended?'#f1f5f9':'#dcfce7',color:ended?'#64748b':'#166534'}}>{ended?'의견등록 종료':'의견등록 가능'}</span></td><td style={{textAlign:'center'}}><button type="button" onClick={e=>toggle(e,i)} aria-label={i.is_interest?'관심 사전규격 해제':'관심 사전규격 등록'} title={i.is_interest?'관심 사전규격 해제':'관심 사전규격 등록'} style={{width:34,height:34,display:'inline-flex',alignItems:'center',justifyContent:'center',borderRadius:'50%',color:i.is_interest?'#ef4444':'#94a3b8',backgroundColor:i.is_interest?'#fef2f2':'transparent',transition:'all .2s'}}><Heart size={19} fill={i.is_interest?'#ef4444':'none'} strokeWidth={2}/></button></td><td style={{fontWeight:700}}><div>{i.title}</div><div style={{fontSize:12,color:'#64748b',marginTop:4}}>{i.spec_no}</div></td><td>{i.org_name}</td><td>{i.estimated_price?`₩ ${Number(i.estimated_price).toLocaleString()}`:'미정'}</td><td>{i.posted_at}</td><td style={{fontWeight:700,color:'#dc2626'}}>{i.deadline_at}</td></tr>})}</tbody></table></div></div></div></Layout>}
